-- ============================================================
-- Migration 003: Update airlines from master list
-- Replace / add all active airlines from operational data
-- ============================================================

INSERT INTO airlines (airline_code, airline_name, status) VALUES
  ('TG',  'Thai Airways',                    'Active'),
  ('XJ',  'Air Asia X',                      'Active'),
  ('FD',  'Air Asia',                        'Active'),
  ('EK',  'Emirates',                        'Active'),
  ('BR',  'EVA Air',                         'Active'),
  ('CX',  'Cathay Pacific Airlines',         'Active'),
  ('QR',  'Qatar Airways',                   'Active'),
  ('SQ',  'Singapore Airlines',              'Active'),
  ('TR',  'Scoot',                           'Active'),
  ('CI',  'China Airlines',                  'Active'),
  ('DD',  'Nok Air',                         'Active'),
  ('SL',  'Thai Lion Air',                   'Active'),
  ('ZE',  'Eastar Jet',                      'Active'),
  ('SU',  'Aeroflot Russian Airlines',       'Active'),
  ('GF',  'Gulf Air',                        'Active'),
  ('EY',  'Etihad Airways',                  'Active'),
  ('HX',  'Hong Kong Airlines',              'Active'),
  ('MM',  'Peach Air',                       'Active'),
  ('VN',  'Vietnam Airlines',                'Active'),
  ('8M',  'Myanmar Airways International',   'Active'),
  ('WE',  'Thai Smile Airways',              'Active'),
  ('HU',  'Hainan Airlines',                 'Active'),
  ('CZ',  'China Southern Airlines',         'Active'),
  ('9W',  'Jet Airways',                     'Active'),
  ('JL',  'Japan Airlines',                  'Active'),
  ('VZ',  'Thai Vietjet Air',                'Active'),
  ('VJ',  'Vietjet Air',                     'Active'),
  ('TK',  'Turkish Airlines',                'Active'),
  ('8L',  'Lucky Air',                       'Active'),
  ('KE',  'Korean Air',                      'Active'),
  ('PR',  'Philippine Airlines',             'Active'),
  ('MS',  'EgyptAir',                        'Active'),
  ('KC',  'Air Astana',                      'Active'),
  ('KU',  'Kuwait Airways',                  'Active'),
  ('HO',  'Juneyao Air',                     'Active'),
  ('QH',  'Bamboo Airways',                  'Active'),
  ('6E',  'IndiGo Airlines',                 'Active'),
  ('OZ',  'Asiana Airlines',                 'Active'),
  ('TW',  'T''way Air',                      'Active'),
  ('OM',  'MIAT Mongolian Airlines',         'Active'),
  ('SG',  'SpiceJet',                        'Active'),
  ('JX',  'Starlux Airlines',                'Active'),
  ('WY',  'Oman Air',                        'Active'),
  ('VU',  'Vietravel Airlines',              'Active'),
  ('UO',  'Hong Kong Express Airways',       'Active'),
  ('KY',  'Kunming Airlines',                'Active'),
  ('9C',  'Spring Airlines',                 'Active'),
  ('BX',  'Air Busan',                       'Active'),
  ('G5',  'China Express Airlines',          'Active'),
  ('JD',  'Beijing Capital Airlines',        'Active'),
  ('ET',  'Ethiopian Airlines',              'Active'),
  ('3U',  'Sichuan Airlines',                'Active'),
  ('FM',  'Shanghai Airlines',               'Active'),
  ('MU',  'China Eastern Airlines',          'Active'),
  ('CA',  'Air China',                       'Active'),
  ('DR',  'Ruili Airlines',                  'Active'),
  ('SV',  'Saudia Airlines',                 'Active'),
  ('QW',  'Qingdao Airlines',                'Active'),
  ('AQ',  '9 Air',                           'Active'),
  ('SC',  'Shandong Airlines',               'Active'),
  ('UQ',  'Urumqi Air',                      'Active'),
  ('ZH',  'Shenzhen Airlines',               'Active'),
  ('HB',  'Greater Bay Airlines',            'Active'),
  ('AI',  'Air India',                       'Active'),
  ('NH',  'All Nippon Airways',              'Active'),
  ('GJ',  'Loong Air',                       'Active'),
  ('BK',  'Okay Airways',                    'Active'),
  ('PN',  'West Air',                        'Active'),
  ('ZG',  'Zego',                            'Active'),
  ('E9',  'Iberojet',                        'Active'),
  ('NX',  'Air Macau',                       'Active'),
  ('EU',  'Chengdu Airlines',                'Active'),
  ('9H',  'Air Chang''an',                   'Active'),
  ('9G',  'Sun Phu Quoc Airways',            'Active')
ON CONFLICT (airline_code) DO UPDATE SET
  airline_name = EXCLUDED.airline_name,
  status       = EXCLUDED.status,
  updated_at   = NOW();

-- Remove airlines that are no longer in the active list
-- (keep those NOT in the new list as-is; only deactivate if explicitly needed)
